const data = {
  data: {
    articles: [
      {
        slug: '1',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '2',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '3',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '4',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '5',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '6',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '7',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '8',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '9',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '10',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '11',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '12',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '13',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '14',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '15',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '16',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '17',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '18',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '19',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
      {
        slug: '20',
        title: 'р',
        description: 'р',
        body: 'ррф',
        createdAt: '2023-01-08T21:02:41.466Z',
        updatedAt: '2023-01-08T21:02:55.447Z',
        tagList: ['р'],
        favorited: false,
        favoritesCount: 0,
        author: {
          username: '123asd123',
          image:
            'https://www.rolls-roycemotorcars.com/content/dam/rrmc/marketUK/rollsroycemotorcars_com/phantom-series-ii-discover/page-properties/Phantom-II-Discover-Hero-Single-Twin-Card.jpg',
          following: false,
        },
      },
    ],
    articlesCount: 200,
  },
}

export { data }
